# Generated by Django 4.0.3 on 2022-03-02 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eppt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='datePublication',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 13, 35, 4, 890439, tzinfo=utc)),
        ),
    ]
