# Generated by Django 4.0.4 on 2022-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
