# Generated by Django 4.0.3 on 2022-03-02 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eppt', '0003_alter_temoignage_datepublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='datePublication',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 13, 40, 31, 593917, tzinfo=utc)),
        ),
    ]
