# Generated by Django 4.0.3 on 2022-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0004_rename_creatrice_temoignages_utilisateurid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
