# Generated by Django 4.0.3 on 2022-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0005_alter_utilisateurs_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
