# Generated by Django 4.0.3 on 2022-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eppt', '0005_alter_temoignage_datepublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text='Entrez le nom de votre prénom', max_length=50)),
                ('nom', models.CharField(help_text='Entrez le nom de votre nom', max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('mdp', models.CharField(max_length=30)),
                ('typeTemoignage', models.CharField(choices=[('L', 'Lyceenne ou collegienne'), ('I', 'Ingenieure ou etudiante ingenieure'), ('A', 'Autre')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='domaineEtude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='region',
            field=models.CharField(choices=[('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'), ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'), ('Bretagne', 'Bretagne'), ('Centre-Val de Loire', 'Centre-Val de Loire'), ('Corse', 'Corse'), ('Grand Est', 'Grand Est'), ('Hauts-de-France', 'Hauts-de-France'), ('Île-de-France', 'Île-de-France'), ('Normandie', 'Normandie'), ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'), ('Occitanie', 'Occitanie'), ('Pays de la Loire', 'Pays de la Loire'), ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur")], max_length=50),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='titreTemoignage',
            field=models.CharField(help_text='Entrez le nom de votre témoignage', max_length=150, unique=True),
        ),
    ]
