# Generated by Django 4.0.3 on 2022-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0007_rename_admin_utilisateurs_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
