# Generated by Django 4.0.3 on 2022-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0008_alter_utilisateurs_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
