# Generated by Django 4.0.3 on 2022-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eppt', '0009_remove_utilisateurs_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
